### ISSUE TITLE
Handling of characters with accents in generation of Citation on Data Package Summary page

### ISSUE THREAD

**Issue by robpayn** [PASTAplus/DataPortal#66] opened 2021-11-06 18:34 UTC
We have a creator with a surname containing an "o" with an acute accent. This all seems to work fine with the list of creators and the personnel details in the full metadata. However, the character does not appear to be handled properly in translation to rendering the Citation on the data package summary page. See package edi.498 on the staging server for an example. Tagging @clnsmth just as an FYI.

**Comment by servilla** [comment] 2021-11-07 15:43
Thanks @robpayn for letting us know about this issue.

The root cause is not associated with the Data Portal, but rather the citation service itself: https://github.com/PASTAplus/cite/issues/13. I'll keep this issue open as a test case for any updates to the citation service, but there is no expected action for the Data Portal.

**Comment by servilla** [comment] 2021-11-11 01:50
See this closing comment: https://github.com/PASTAplus/cite/issues/13#issuecomment-965918340

**Closed by servilla** 2021-11-11 01:50 UTC
Labels: bug
